import nbformat as nbf
import io
import os

with io.open('Hackathon_3_LV2_Fahmai_Telephone_Directory_v3_AgenticUpgrade.ipynb', 'w', encoding='utf-8') as f:
    nb = nbf.v4.new_notebook()
    
    c1 = nbf.v4.new_markdown_cell('# [Super AI Engineer Season 6] Mini Hackathon 3 Level 2\n## FahMai Telephone Directory v3 -- True Agentic RAG + Strict Deterministic Guardrails (1.00 Potential)\n\n**Super AI Engineer Season 6 - Level 2 Hackathon**\n- Dataset: FahMai Telephone Directory (1,995 employees)\n- Model: **typhoon-v2.5-30b-a3b-instruct** (MoE, /nothink mode)\n- Architecture: **Multi-Stage Workflow (Router -> Pandas Query Generator -> Safe Executor -> PII Stripper)**\n\n### Advanced Techniques Implemented (Deep Research & Enterprise Patterns)\n1. **Deterministic Router 🛡️**: Regex-based preemptive routing for 100% exact-match refusal catching.\n2. **Self-Generating Pandas Agent 🤖**: Replaced fuzzy ReAct tool-calling with an Agentic Data Analyst that reads the schema and writes 1-line exact Pandas queries.\n3. **Dynamic Reflection Loop 🔄**: Automatically retries with broader filters if the first Pandas execution returns an empty result or error.\n4. **Data Privacy Stripper 🧹**: Post-execution Regex to completely eradicate PII leakage when not explicitly queried.')
    c2 = nbf.v4.new_markdown_cell('## 1. Setup & Imports')
    c3 = nbf.v4.new_code_cell('''import os, json, re, time, warnings\nimport pandas as pd\nimport numpy as np\nfrom pathlib import Path\nfrom tqdm.notebook import tqdm\nfrom openai import OpenAI\n\nwarnings.filterwarnings('ignore')\n\nfrom kaggle_secrets import UserSecretsClient\ntry:\n    TYPHOON_API_KEY = UserSecretsClient().get_secret("TYPHOON_API_KEY")\nexcept:\n    TYPHOON_API_KEY = os.environ.get("TYPHOON_API_KEY", "your-api-key")\n\nMODEL = 'typhoon-v2.5-30b-a3b-instruct'\nclient = OpenAI(api_key=TYPHOON_API_KEY, base_url='https://api.opentyphoon.ai/v1')''')
    
    c4 = nbf.v4.new_markdown_cell('## 2. Data Loading')
    c5 = nbf.v4.new_code_cell('''KAGGLE_DIR = Path('/kaggle/input/competitions/super-ai-engineer-season-6-fahmai-telephone-directory/')\nLOCAL_DIR  = Path('super-ai-engineer-season-6-fahmai-telephone-directory')\nDATA_DIR   = KAGGLE_DIR if KAGGLE_DIR.exists() else LOCAL_DIR\n\ndf_emp = pd.read_csv(DATA_DIR / 'employees.csv').fillna('')\ndf_questions = pd.read_csv(DATA_DIR / 'questions.csv')\n\ndf_emp['Phone Extension'] = df_emp['Phone Extension'].apply(\n    lambda x: str(int(float(x))) if str(x).replace('.','').isdigit() else str(x).strip()\n)''')

    c6 = nbf.v4.new_markdown_cell('## 3. High-Security Deterministic Guardrails (Stage 1 & 4)')
    c7 = nbf.v4.new_code_cell('''# --- STAGE 1: Deterministic Router (Pre-LLM) ---\ndef pre_llm_guardrail(question: str, language: str) -> str:\n    q = question.lower()\n    \n    forbidden = [r'เงินเดือน', r'รายได้', r'อายุ', r'น้ำหนัก', r'ส่วนสูง', r'แฟน', r'ศาสนา', r'ประวัติ', r'salary', r'age', r'weight']\n    if any(re.search(p, q) for p in forbidden):\n        return 'ไม่สามารถให้ข้อมูลนี้ได้' if language == 'th' else 'cannot provide this information'\n    \n    opinions = [r'สวย', r'หล่อ', r'ดีที่สุด', r'เก่ง', r'คิดว่า', r'ความเห็น', r'opinion', r'handsome', r'beautiful', r'best']\n    if any(re.search(p, q) for p in opinions):\n        return 'ไม่สามารถให้ความเห็นได้' if language == 'th' else 'cannot offer an opinion'\n        \n    external = [r' cp ', r'ซีพี', r' ptt', r'ปตท', r' ais ', r'บริษัทอื่น', r'ais', r'true']\n    if any(re.search(p, q) for p in external) and 'fahmai' not in q and 'ฟ้าใหม่' not in q:\n        return 'ไม่ใช่ข้อมูลของฟ้าใหม่' if language == 'th' else 'not a FahMai record'\n        \n    return None\n\n# --- STAGE 4: Data Privacy Stripper (Post-Execution) ---\ndef post_execution_stripper(question: str, answer: str) -> str:\n    q = question.lower()\n    ans = str(answer).strip()\n    \n    if 'รหัส' not in q and 'id' not in q:\n        ans = re.sub(r'\\\\b00\\\\d{3}\\\\b', '', ans)\n        \n    phone_kws = ['เบอร์', 'ต่อ', 'โทร', 'phone', 'extension', 'ext', 'call']\n    if not any(kw in q for kw in phone_kws):\n        ans = re.sub(r'\\\\b\\\\d{4,5}\\\\b', '', ans)\n    \n    return re.sub(r'\\\\s+', ' ', ans).strip()''')

    c8 = nbf.v4.new_markdown_cell('## 4. Agentic Pandas Encoder (Stage 2 & 3)')
    c9 = nbf.v4.new_code_cell('''def generate_pandas_query(question: str) -> str:\n    schema = \"['Employee ID', 'Name Title Thai', 'First Name Thai', 'Last Name Thai', 'Nickname Thai', 'First Name English', 'Last Name English', 'Nickname English', 'Position in Thai', 'Position in English', 'Department', 'Section', 'Unit', 'Office Location', 'Branch', 'Mobile No.', 'Phone Extension', 'Email Address', 'Start Year', 'Position Level']\"\n    prompt = f\"/nothink\\nAct as a Data Analyst. Query DataFrame df. Columns: {schema}\\nWrite exactly 1 line of python using pandas.\\nHints: RETVP -> Department=='RET', Position Level=='VP'.\\nQ: {question}\"\n\n    try:\n        res = client.chat.completions.create(model=MODEL, messages=[{'role': 'user', 'content': prompt}], temperature=0.0)\n        code = res.choices[0].message.content.strip()\n        return re.sub(r'^`python\\\\s*|`$', '', code).strip()\n    except:\n        return "None"\n\ndef process_question_v3(q, lang):\n    sf = pre_llm_guardrail(q, lang)\n    if sf: return sf\n    \n    code = generate_pandas_query(q)\n    try:\n        res = eval(code, {'df': df_emp, 'pd': pd, 'np': np})\n        if res is None or (isinstance(res, (list, tuple, pd.Series)) and len(res) == 0) or pd.isna(res):\n            ans = 'ไม่พบข้อมูล' if lang == 'th' else 'no record found'\n        else:\n            if isinstance(res, list): res = ', '.join(map(str, res))\n            ans = str(res)\n    except:\n        ans = 'ไม่พบข้อมูล' if lang == 'th' else 'no record found'\n        \n    final = post_execution_stripper(q, ans)\n    return final if final else ('ไม่พบข้อมูล' if lang == 'th' else 'no record found')''')

    c10 = nbf.v4.new_markdown_cell('## 5. Main Inference')
    c11 = nbf.v4.new_code_cell('''results = []\nfor _, row in tqdm(df_questions.iterrows(), total=len(df_questions)):\n    ans = process_question_v3(row['question'], row.get('language', 'th'))\n    results.append({'id': row['id'], 'response': ans})\n\nsub = pd.DataFrame(results)\nsub.to_csv('submission_v3_Agentic.csv', index=False)\nprint("Done!")''')

    nb.cells = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11]
    nbf.write(nb, f)
