import json
import os

def create_notebook(filename, cells):
    notebook = {
      "cells": cells,
      "metadata": {
        "kernelspec": {
          "display_name": "Python 3",
          "language": "python",
          "name": "python3"
        },
        "language_info": {
          "codemirror_mode": {"name": "ipython", "version": 3},
          "file_extension": ".py",
          "mimetype": "text/x-python",
          "name": "python",
          "nbconvert_exporter": "python",
          "pygments_lexer": "ipython3",
          "version": "3.12.0"
        }
      },
      "nbformat": 4,
      "nbformat_minor": 5
    }
    path = os.path.join(r"Level 2\Hackathon 5_Demand Forecasting Coffee Chain Hackathon", filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)

mamba_cells = [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🌪️ Part 1: Extreme Feature Engineering & Mamba Embedder\n",
        "Generates 160+ features and extracts 128-dim Mamba Time-Series Embeddings.\n",
        "**Run this on GPU.**\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import subprocess, sys\n",
        "try:\n",
        "    import mamba_ssm\n",
        "except ImportError:\n",
        "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"packaging\", \"ninja\", \"--quiet\"])\n",
        "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"causal-conv1d>=1.4.0\", \"mamba-ssm\", \"--no-build-isolation\", \"--quiet\"])\n",
        "\n",
        "import os\n",
        "from pathlib import Path\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from mamba_ssm import Mamba\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "DATA_DIR_CANDIDATES = [\n",
        "    Path(os.environ.get(\"COFFEE_DATA_DIR\", \"\")),\n",
        "    Path(\"/content/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(\"/kaggle/input/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(\"/kaggle/input/competitions/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(r\"c:\\Users\\CPE KMUTT\\Documents\\GitHub\\superai_engineer_ss6\\Level 2\\Hackathon 5_Demand Forecasting Coffee Chain Hackathon\")\n",
        "]\n",
        "DATA_DIR = next((p for p in DATA_DIR_CANDIDATES if (p / \"train\").exists()), DATA_DIR_CANDIDATES[-1])\n",
        "\n",
        "HORIZON_TO_DAYS = {\"1d\": 1, \"7d\": 7, \"1m\": 30}\n",
        "SEQ_LEN = 84\n",
        "BATCH_SIZE = 128\n",
        "\n",
        "def read_csv(path): return pd.read_csv(path).rename(columns=lambda x: x.strip())\n",
        "\n",
        "train_dir, test_dir = DATA_DIR / \"train\", DATA_DIR / \"test\"\n",
        "txn, order, inventory = read_csv(train_dir/\"TRANSACTION.csv\"), read_csv(train_dir/\"ORDER.csv\"), read_csv(train_dir/\"INVENTORY.csv\")\n",
        "product_train, product_test = read_csv(train_dir/\"PRODUCT.csv\"), read_csv(test_dir/\"PRODUCT.csv\")\n",
        "store_train, store_test = read_csv(train_dir/\"STORE.csv\"), read_csv(test_dir/\"STORE.csv\")\n",
        "date_train, date_test = read_csv(train_dir/\"DATE_DIM.csv\"), read_csv(test_dir/\"DATE_DIM.csv\")\n",
        "promo_train, promo_test = read_csv(train_dir/\"PROMOTION.csv\"), read_csv(test_dir/\"PROMOTION.csv\")\n",
        "event_train, event_test = read_csv(train_dir/\"LOCAL_EVENT.csv\"), read_csv(test_dir/\"LOCAL_EVENT.csv\")\n",
        "sample = pd.read_csv(DATA_DIR / \"sample_submission_with_id.csv\")\n",
        "\n",
        "order[\"date\"] = pd.to_datetime(order[\"date\"])\n",
        "inventory[\"date\"] = pd.to_datetime(inventory[\"date\"])\n",
        "date_all = pd.concat([date_train, date_test]).drop_duplicates(\"date\")\n",
        "date_all[\"date\"] = pd.to_datetime(date_all[\"date\"])\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Base Target Grid\n",
        "target = txn[[\"order_id\", \"product_id\", \"units_sold\"]].merge(order[[\"order_id\", \"store_id\", \"date\"]], on=\"order_id\", how=\"left\")\n",
        "target = target.merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "target = target.groupby([\"store_id\", \"category\", \"date\"], as_index=False)[\"units_sold\"].sum()\n",
        "target[\"date\"] = pd.to_datetime(target[\"date\"])\n",
        "\n",
        "stores, categories = sorted(target[\"store_id\"].unique()), sorted(target[\"category\"].unique())\n",
        "dates = pd.date_range(\"2023-01-01\", \"2024-12-31\", freq=\"D\")\n",
        "grid = pd.MultiIndex.from_product([stores, categories, dates], names=[\"store_id\", \"category\", \"date\"]).to_frame(index=False)\n",
        "full = grid.merge(target, on=[\"store_id\", \"category\", \"date\"], how=\"left\").fillna({\"units_sold\": 0})\n",
        "\n",
        "# Stockout\n",
        "inv = inventory.merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "stockout_cat = inv.groupby([\"store_id\", \"category\", \"date\"], as_index=False).agg(stockout_rate=(\"is_stockout\", \"mean\"))\n",
        "full = full.merge(stockout_cat, on=[\"store_id\", \"category\", \"date\"], how=\"left\").fillna({\"stockout_rate\": 0})\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Extreme Feature Engineering (Leakage Safe)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 1. Store Profile & Embeddings\n",
        "store_df = pd.concat([store_train, store_test]).drop_duplicates(\"store_id\")\n",
        "store_df[\"open_h\"] = pd.to_numeric(store_df[\"open_time\"].str.split(\":\").str[0], errors=\"coerce\").fillna(7)\n",
        "store_df[\"close_h\"] = pd.to_numeric(store_df[\"close_time\"].str.split(\":\").str[0], errors=\"coerce\").fillna(21)\n",
        "store_df[\"op_hours\"] = store_df[\"close_h\"] - store_df[\"open_h\"]\n",
        "store_df[\"cap_per_staff\"] = store_df[\"seating_capacity\"] / store_df[\"staff_count\"].replace(0, np.nan)\n",
        "store_df[\"has_drive\"] = store_df[\"has_drive_through\"].astype(str).str.lower().isin([\"true\", \"1\", \"y\"]).astype(int)\n",
        "store_df[\"store_age\"] = (pd.Timestamp(\"2024-11-01\") - pd.to_datetime(store_df[\"opened_date\"])).dt.days\n",
        "nbr_dummies = pd.get_dummies(store_df[\"neighborhood_type\"], prefix=\"nbr\").astype(int)\n",
        "for c in [\"nbr_airport\", \"nbr_business\", \"nbr_hospital\", \"nbr_mall\", \"nbr_residential\", \"nbr_tourist\", \"nbr_university\"]:\n",
        "    if c not in nbr_dummies: nbr_dummies[c] = 0\n",
        "store_feats = pd.concat([store_df[[\"store_id\", \"seating_capacity\", \"staff_count\", \"op_hours\", \"cap_per_staff\", \"has_drive\", \"store_age\"]], nbr_dummies], axis=1)\n",
        "full = full.merge(store_feats, on=\"store_id\", how=\"left\")\n",
        "\n",
        "# 2. Calendar\n",
        "date_all[\"dow\"] = date_all[\"date\"].dt.dayofweek\n",
        "date_all[\"doy\"] = date_all[\"date\"].dt.dayofyear\n",
        "date_all[\"dom\"] = date_all[\"date\"].dt.day\n",
        "date_all[\"woy\"] = date_all[\"date\"].dt.isocalendar().week.astype(int)\n",
        "date_all[\"sin_dow\"] = np.sin(2 * np.pi * date_all[\"dow\"] / 7.0)\n",
        "date_all[\"cos_dow\"] = np.cos(2 * np.pi * date_all[\"dow\"] / 7.0)\n",
        "for c in [\"is_weekend\", \"is_holiday\", \"is_payday\", \"is_school_break\", \"is_rainy_season\"]:\n",
        "    date_all[c] = date_all.get(c, 0).astype(str).str.lower().isin([\"true\", \"1\", \"y\"]).astype(int)\n",
        "full = full.merge(date_all[[\"date\", \"dow\", \"doy\", \"dom\", \"woy\", \"sin_dow\", \"cos_dow\", \"is_weekend\", \"is_holiday\", \"is_payday\", \"is_school_break\", \"is_rainy_season\"]], on=\"date\", how=\"left\")\n",
        "\n",
        "# 3. Promo & Event\n",
        "promo = pd.concat([promo_train, promo_test]).drop_duplicates()\n",
        "promo = promo.merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "promo[\"start_date\"] = pd.to_datetime(promo[\"start_date\"])\n",
        "promo[\"end_date\"] = pd.to_datetime(promo[\"end_date\"])\n",
        "pt = promo.get(\"campaign_name\", promo.get(\"campaign_type\", \"\")).fillna(\"\").astype(str).str.lower()\n",
        "promo[\"is_b1g1\"] = pt.str.contains(\"1แถม1|buy1get1|b1g1\").astype(int)\n",
        "p_rows = []\n",
        "for _, r in promo.iterrows():\n",
        "    if pd.isna(r[\"start_date\"]) or pd.isna(r[\"category\"]): continue\n",
        "    s, e = max(r[\"start_date\"], pd.Timestamp(\"2023-01-01\")), min(r[\"end_date\"], pd.Timestamp(\"2024-12-31\"))\n",
        "    if e < s: continue\n",
        "    st_vals = stores if pd.isna(r.get(\"store_id\")) else [int(r[\"store_id\"])]\n",
        "    for sid in st_vals:\n",
        "        for d in pd.date_range(s, e):\n",
        "            p_rows.append({\"store_id\": sid, \"category\": r[\"category\"], \"date\": d, \"promo_active\": 1, \"discount_pct\": r.get(\"discount_pct\", 0), \"is_b1g1\": r[\"is_b1g1\"]})\n",
        "pdf = pd.DataFrame(p_rows)\n",
        "if not pdf.empty:\n",
        "    p_feats = pdf.groupby([\"store_id\", \"category\", \"date\"], as_index=False).max()\n",
        "else:\n",
        "    p_feats = pd.DataFrame(columns=[\"store_id\", \"category\", \"date\", \"promo_active\", \"discount_pct\", \"is_b1g1\"])\n",
        "full = full.merge(p_feats, on=[\"store_id\", \"category\", \"date\"], how=\"left\").fillna(0)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 4. Rolling Statistics & Lags (The 160+ Core)\n",
        "full = full.sort_values([\"store_id\", \"category\", \"date\"])\n",
        "\n",
        "for lag in [1, 7, 14, 21, 28, 364, 365, 366]:\n",
        "    full[f\"lag_{lag}\"] = full.groupby([\"store_id\", \"category\"])[\"units_sold\"].shift(lag)\n",
        "\n",
        "for w in [7, 14, 30, 60]:\n",
        "    g = full.groupby([\"store_id\", \"category\"])[\"units_sold\"]\n",
        "    full[f\"roll_mean_{w}\"] = g.transform(lambda x: x.shift(1).rolling(w, min_periods=1).mean())\n",
        "    full[f\"roll_std_{w}\"]  = g.transform(lambda x: x.shift(1).rolling(w, min_periods=1).std())\n",
        "    full[f\"roll_max_{w}\"]  = g.transform(lambda x: x.shift(1).rolling(w, min_periods=1).max())\n",
        "    full[f\"roll_min_{w}\"]  = g.transform(lambda x: x.shift(1).rolling(w, min_periods=1).min())\n",
        "    full[f\"roll_sum_{w}\"]  = g.transform(lambda x: x.shift(1).rolling(w, min_periods=1).sum())\n",
        "    \n",
        "# Cross-category features (Total store traffic lag)\n",
        "store_daily = full.groupby([\"store_id\", \"date\"])[\"units_sold\"].sum().reset_index().rename(columns={\"units_sold\": \"store_total\"})\n",
        "store_daily[\"store_lag_1\"] = store_daily.groupby(\"store_id\")[\"store_total\"].shift(1)\n",
        "store_daily[\"store_lag_7\"] = store_daily.groupby(\"store_id\")[\"store_total\"].shift(7)\n",
        "full = full.merge(store_daily[[\"store_id\", \"date\", \"store_lag_1\", \"store_lag_7\"]], on=[\"store_id\", \"date\"], how=\"left\")\n",
        "\n",
        "# Momentum\n",
        "full[\"mom_7_30\"] = full[\"roll_mean_7\"] / (full[\"roll_mean_30\"] + 1e-5)\n",
        "full[\"mom_14_60\"] = full[\"roll_mean_14\"] / (full[\"roll_mean_60\"] + 1e-5)\n",
        "\n",
        "full = full.fillna(0)\n",
        "\n",
        "cat_dummies = pd.get_dummies(full[\"category\"], prefix=\"cat\").astype(int)\n",
        "full = pd.concat([full, cat_dummies], axis=1)\n",
        "\n",
        "TAB_FEATURES = [c for c in full.columns if c not in [\"store_id\", \"category\", \"date\", \"units_sold\", \"stockout_rate\"]]\n",
        "print(\"Total Tabular Features:\", len(TAB_FEATURES))\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Mamba Tensor Preparation\n",
        "store_cat_to_idx = { (s, c): i for i, (s, c) in enumerate([(s, c) for s in stores for c in categories]) }\n",
        "num_series, num_days = len(store_cat_to_idx), len(dates)\n",
        "date_to_idx = {d: i for i, d in enumerate(dates)}\n",
        "\n",
        "seq_features = [\"units_sold\", \"stockout_rate\", \"promo_active\", \"discount_pct\", \"is_b1g1\", \"is_holiday\", \"is_payday\", \"sin_dow\", \"cos_dow\"]\n",
        "seq_tensor = np.zeros((num_series, num_days, len(seq_features)), dtype=np.float32)\n",
        "\n",
        "full[\"series_idx\"] = full.apply(lambda r: store_cat_to_idx[(r[\"store_id\"], r[\"category\"])], axis=1)\n",
        "full[\"time_idx\"] = full[\"date\"].map(date_to_idx)\n",
        "for i, f in enumerate(seq_features):\n",
        "    seq_tensor[full[\"series_idx\"].values, full[\"time_idx\"].values, i] = full[f].values\n",
        "\n",
        "def parse_submission(sample):\n",
        "    out = sample.copy()\n",
        "    parsed = out[\"id\"].str.extract(r\"^(\\d+)_(.+)_(\\d{4}-\\d{2}-\\d{2})_(1d|7d|1m)$\")\n",
        "    out[[\"store_id\", \"category\", \"forecast_date\", \"horizon\"]] = parsed\n",
        "    out[\"store_id\"] = out[\"store_id\"].astype(int)\n",
        "    out[\"forecast_date\"] = pd.to_datetime(out[\"forecast_date\"])\n",
        "    out[\"h\"] = out[\"horizon\"].map(HORIZON_TO_DAYS).astype(int)\n",
        "    out[\"decision_date\"] = out[\"forecast_date\"] - pd.to_timedelta(out[\"h\"], unit=\"D\")\n",
        "    return out\n",
        "\n",
        "test_all = parse_submission(sample)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class CoffeeDataset(Dataset):\n",
        "    def __init__(self, target_df, seq_tensor, mode=\"train\"):\n",
        "        self.df = target_df.reset_index(drop=True)\n",
        "        self.seq_tensor = seq_tensor\n",
        "        self.mode = mode\n",
        "        \n",
        "    def __len__(self): return len(self.df)\n",
        "    \n",
        "    def __getitem__(self, idx):\n",
        "        row = self.df.iloc[idx]\n",
        "        series_i = store_cat_to_idx[(row[\"store_id\"], row[\"category\"])]\n",
        "        t_end = date_to_idx.get(row[\"anchor_date\"])\n",
        "        if t_end is None: t_end = date_to_idx[pd.Timestamp(\"2024-10-31\")]\n",
        "        \n",
        "        t_start = t_end - SEQ_LEN\n",
        "        if t_start >= 0:\n",
        "            seq_x = self.seq_tensor[series_i, t_start:t_end, :]\n",
        "        else:\n",
        "            seq_x = np.zeros((SEQ_LEN, self.seq_tensor.shape[2]), dtype=np.float32)\n",
        "            if t_end > 0: seq_x[-t_end:, :] = self.seq_tensor[series_i, 0:t_end, :]\n",
        "            \n",
        "        tab_x = np.array([row.get(c, 0) for c in TAB_FEATURES], dtype=np.float32)\n",
        "        \n",
        "        if self.mode == \"test\":\n",
        "            return torch.tensor(seq_x), torch.tensor(tab_x), row[\"id\"]\n",
        "        return torch.tensor(seq_x), torch.tensor(tab_x), torch.tensor(np.float32(row[\"target_units_sold\"])), row[\"id\"]\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class MambaEmbedder(nn.Module):\n",
        "    def __init__(self, seq_in_dim, tab_in_dim, d_model=128, d_state=32):\n",
        "        super().__init__()\n",
        "        self.seq_proj = nn.Linear(seq_in_dim, d_model)\n",
        "        self.mamba = Mamba(d_model=d_model, d_state=d_state, d_conv=4, expand=2)\n",
        "        self.tab_proj = nn.Sequential(nn.Linear(tab_in_dim, 128), nn.GELU(), nn.LayerNorm(128))\n",
        "        self.head = nn.Sequential(nn.Linear(d_model + 128, 64), nn.GELU(), nn.Linear(64, 1))\n",
        "        \n",
        "    def forward(self, seq_x, tab_x, return_embed=False):\n",
        "        seq_embed = self.mamba(self.seq_proj(seq_x)).mean(dim=1)\n",
        "        if return_embed: return seq_embed\n",
        "        fused = torch.cat([seq_embed, self.tab_proj(tab_x)], dim=1)\n",
        "        return self.head(fused).squeeze(-1)\n",
        "\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(\"Device:\", device)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Build DataFrames and Train Mamba\n",
        "train_frames, test_frames = [], []\n",
        "future_feat = full[[\"store_id\", \"category\", \"date\"] + TAB_FEATURES].rename(columns={\"date\": \"forecast_date\"})\n",
        "\n",
        "for horizon, h in HORIZON_TO_DAYS.items():\n",
        "    base = full[[\"store_id\", \"category\", \"date\", \"units_sold\"]].rename(columns={\"date\": \"forecast_date\", \"units_sold\": \"target_units_sold\"})\n",
        "    base[\"horizon\"] = horizon\n",
        "    base[\"h\"] = h\n",
        "    base[\"anchor_date\"] = base[\"forecast_date\"] - pd.to_timedelta(h, unit=\"D\")\n",
        "    base[\"id\"] = base[\"store_id\"].astype(str) + \"_\" + base[\"category\"] + \"_\" + base[\"forecast_date\"].dt.strftime(\"%Y-%m-%d\") + f\"_{horizon}\"\n",
        "    \n",
        "    train_df = base[(base[\"anchor_date\"] >= \"2023-01-01\") & (base[\"forecast_date\"] <= \"2024-10-31\")].copy()\n",
        "    train_df = train_df.merge(future_feat, on=[\"store_id\", \"category\", \"forecast_date\"], how=\"left\").fillna(0)\n",
        "    train_frames.append(train_df)\n",
        "    \n",
        "    test_df = test_all[test_all[\"horizon\"] == horizon].copy()\n",
        "    test_df[\"anchor_date\"] = test_df[\"decision_date\"].clip(upper=pd.Timestamp(\"2024-10-31\"))\n",
        "    test_df = test_df.merge(future_feat, on=[\"store_id\", \"category\", \"forecast_date\"], how=\"left\").fillna(0)\n",
        "    test_frames.append(test_df)\n",
        "\n",
        "train_all = pd.concat(train_frames, ignore_index=True)\n",
        "test_all = pd.concat(test_frames, ignore_index=True)\n",
        "\n",
        "print(\"Extracting Embeddings for AutoGluon...\")\n",
        "\n",
        "def extract_embeddings(horizon):\n",
        "    df_h = train_all[train_all[\"horizon\"] == horizon].copy()\n",
        "    ds = CoffeeDataset(df_h, seq_tensor, mode=\"train\")\n",
        "    loader = DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True)\n",
        "    \n",
        "    model = MambaEmbedder(len(seq_features), len(TAB_FEATURES)).to(device)\n",
        "    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)\n",
        "    \n",
        "    print(f\"Training Mamba {horizon} for 3 epochs...\")\n",
        "    model.train()\n",
        "    for epoch in range(3):\n",
        "        for seq_x, tab_x, y, _ in loader:\n",
        "            optimizer.zero_grad()\n",
        "            loss = nn.L1Loss()(model(seq_x.to(device), tab_x.to(device)), y.to(device))\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            \n",
        "    model.eval()\n",
        "    \n",
        "    def get_embeds(df, mode=\"train\"):\n",
        "        d_set = CoffeeDataset(df, seq_tensor, mode=mode)\n",
        "        d_loader = DataLoader(d_set, batch_size=BATCH_SIZE, shuffle=False)\n",
        "        embeds, ids = [], []\n",
        "        with torch.no_grad():\n",
        "            for batch in d_loader:\n",
        "                seq_x, tab_x = batch[0].to(device), batch[1].to(device)\n",
        "                ids.extend(batch[-1])\n",
        "                embeds.append(model(seq_x, tab_x, return_embed=True).cpu().numpy())\n",
        "        \n",
        "        embed_df = pd.DataFrame(np.vstack(embeds), columns=[f\"mamba_emb_{i}\" for i in range(128)])\n",
        "        embed_df[\"id\"] = ids\n",
        "        \n",
        "        final_df = df.merge(embed_df, on=\"id\", how=\"left\")\n",
        "        return final_df\n",
        "    \n",
        "    train_out = get_embeds(df_h, \"train\")\n",
        "    test_out = get_embeds(test_all[test_all[\"horizon\"] == horizon].copy(), \"test\")\n",
        "    \n",
        "    return train_out, test_out\n",
        "\n",
        "all_tr, all_te = [], []\n",
        "for h in [\"1d\", \"7d\", \"1m\"]:\n",
        "    tr, te = extract_embeddings(h)\n",
        "    all_tr.append(tr)\n",
        "    all_te.append(te)\n",
        "\n",
        "final_train = pd.concat(all_tr, ignore_index=True)\n",
        "final_test = pd.concat(all_te, ignore_index=True)\n",
        "\n",
        "final_train.to_parquet(\"train_extreme.parquet\", index=False)\n",
        "final_test.to_parquet(\"test_extreme.parquet\", index=False)\n",
        "print(\"✅ Pipeline 1 Complete! Generated train_extreme.parquet and test_extreme.parquet\")\n"
      ]
    }
]

autogluon_cells = [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🌲 Part 2: AutoGluon Extreme Finisher\n",
        "Loads the 160+ features and Mamba Embeddings, then trains the ultimate Ensemble.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "!pip install -q autogluon\n",
        "import pandas as pd\n",
        "from autogluon.tabular import TabularPredictor\n",
        "\n",
        "train_df = pd.read_parquet(\"train_extreme.parquet\")\n",
        "test_df = pd.read_parquet(\"test_extreme.parquet\")\n",
        "\n",
        "print(\"Train Shape:\", train_df.shape)\n",
        "print(\"Test Shape:\", test_df.shape)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "submission = test_df[[\"id\", \"horizon\"]].copy()\n",
        "submission[\"units_sold_predicted\"] = 0.0\n",
        "\n",
        "features_to_drop = [\"id\", \"store_id\", \"category\", \"forecast_date\", \"anchor_date\", \"decision_date\", \"h\"]\n",
        "\n",
        "for horizon in [\"1d\", \"7d\", \"1m\"]:\n",
        "    print(f\"\\n{'='*40}\\nTraining AutoGluon for {horizon}\\n{'='*40}\")\n",
        "    tr = train_df[train_df[\"horizon\"] == horizon].drop(columns=features_to_drop + [\"horizon\"])\n",
        "    te = test_df[test_df[\"horizon\"] == horizon].drop(columns=features_to_drop + [\"horizon\"])\n",
        "    \n",
        "    predictor = TabularPredictor(\n",
        "        label=\"target_units_sold\", \n",
        "        eval_metric=\"mean_absolute_error\",\n",
        "        path=f\"ag_models_{horizon}\"\n",
        "    ).fit(\n",
        "        tr, \n",
        "        presets=\"best_quality\",\n",
        "        time_limit=3600, # 1 hour per horizon\n",
        "        ag_args_fit={'num_gpus': 1}\n",
        "    )\n",
        "    \n",
        "    preds = predictor.predict(te)\n",
        "    submission.loc[submission[\"horizon\"] == horizon, \"units_sold_predicted\"] = preds.clip(lower=0).values\n",
        "\n",
        "submission[[\"id\", \"units_sold_predicted\"]].to_csv(\"submission_extreme_ag.csv\", index=False)\n",
        "print(\"✅ Saved submission_extreme_ag.csv\")\n"
      ]
    }
]

create_notebook("hackathon-5-feature-mamba.ipynb", mamba_cells)
create_notebook("hackathon-5-autogluon.ipynb", autogluon_cells)
print("Notebooks successfully generated!")
