import json

notebook = {
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🚀 Coffee Chain Demand Forecasting - Mamba SSM Hybrid (v2: Deep Context Edition)\n",
        "This notebook utilizes **Mamba (State Space Model)** to extract deep temporal patterns from the raw 84-day historical sequence, combined with an MLP for 45+ tabular covariates (promos, events, annual lags, and store capacity).\n",
        "\n",
        "> ⚠️ **REQUIREMENT:** This notebook MUST be run with a GPU (e.g., Kaggle T4x2 or P100). `mamba-ssm` requires CUDA to compile and run its fast kernels.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Install dependencies for Mamba SSM (Fix for Kaggle Wheel Building)\n",
        "import subprocess\n",
        "import sys\n",
        "\n",
        "try:\n",
        "    import mamba_ssm\n",
        "    print(\"mamba-ssm is already installed!\")\n",
        "except ImportError:\n",
        "    print(\"Installing packaging and ninja to support building causal-conv1d/mamba-ssm...\")\n",
        "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"packaging\", \"ninja\", \"--quiet\"])\n",
        "    print(\"Installing causal-conv1d and mamba-ssm...\")\n",
        "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", \"causal-conv1d>=1.4.0\", \"mamba-ssm\", \"--no-build-isolation\", \"--quiet\"])\n",
        "    print(\"Installation complete!\")\n",
        "\n",
        "import os\n",
        "from pathlib import Path\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from mamba_ssm import Mamba\n",
        "\n",
        "pd.set_option(\"display.max_columns\", 120)\n",
        "pd.set_option(\"display.width\", 180)\n",
        "\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(\"Using device:\", device)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 1. Data Setup & Loading\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "DATA_DIR_CANDIDATES = [\n",
        "    Path(os.environ.get(\"COFFEE_DATA_DIR\", \"\")),\n",
        "    Path(\"/content/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(\"/kaggle/input/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(\"/kaggle/input/competitions/super-ai-engineer-season-6-coffee-chain-hackathon\"),\n",
        "    Path(r\"c:\\Users\\CPE KMUTT\\Documents\\GitHub\\superai_engineer_ss6\\Level 2\\Hackathon 5_Demand Forecasting Coffee Chain Hackathon\")\n",
        "]\n",
        "DATA_DIR = next((p for p in DATA_DIR_CANDIDATES if (p / \"train\").exists()), DATA_DIR_CANDIDATES[-1])\n",
        "\n",
        "OUTPUT_PATH = Path(\"submission_mamba_hybrid.csv\")\n",
        "\n",
        "TRAIN_START = pd.Timestamp(\"2023-01-01\")\n",
        "TRAIN_END = pd.Timestamp(\"2024-10-31\")\n",
        "VALID_START = pd.Timestamp(\"2023-12-01\")\n",
        "VALID_END = pd.Timestamp(\"2023-12-31\")\n",
        "\n",
        "HORIZON_TO_DAYS = {\"1d\": 1, \"7d\": 7, \"1m\": 30}\n",
        "SEQ_LEN = 84 # Look back 12 weeks\n",
        "BATCH_SIZE = 128\n",
        "EPOCHS = 12\n",
        "LR = 1e-3\n",
        "\n",
        "def read_csv(path: Path) -> pd.DataFrame:\n",
        "    df = pd.read_csv(path)\n",
        "    df.columns = [c.strip() for c in df.columns]\n",
        "    return df\n",
        "\n",
        "train_dir = DATA_DIR / \"train\"\n",
        "test_dir = DATA_DIR / \"test\"\n",
        "\n",
        "txn = read_csv(train_dir / \"TRANSACTION.csv\")\n",
        "order = read_csv(train_dir / \"ORDER.csv\")\n",
        "inventory = read_csv(train_dir / \"INVENTORY.csv\")\n",
        "promo_train = read_csv(train_dir / \"PROMOTION.csv\")\n",
        "event_train = read_csv(train_dir / \"LOCAL_EVENT.csv\")\n",
        "date_train = read_csv(train_dir / \"DATE_DIM.csv\")\n",
        "store_train = read_csv(train_dir / \"STORE.csv\")\n",
        "product_train = read_csv(train_dir / \"PRODUCT.csv\")\n",
        "\n",
        "promo_test = read_csv(test_dir / \"PROMOTION.csv\")\n",
        "event_test = read_csv(test_dir / \"LOCAL_EVENT.csv\")\n",
        "date_test = read_csv(test_dir / \"DATE_DIM.csv\")\n",
        "store_test = read_csv(test_dir / \"STORE.csv\")\n",
        "product_test = read_csv(test_dir / \"PRODUCT.csv\")\n",
        "\n",
        "sample = pd.read_csv(DATA_DIR / \"sample_submission.csv\") if (DATA_DIR / \"sample_submission.csv\").exists() else pd.read_csv(DATA_DIR / \"sample_submission_with_id.csv\")\n",
        "\n",
        "order[\"date\"] = pd.to_datetime(order[\"date\"])\n",
        "inventory[\"date\"] = pd.to_datetime(inventory[\"date\"])\n",
        "date_train[\"date\"] = pd.to_datetime(date_train[\"date\"])\n",
        "date_test[\"date\"] = pd.to_datetime(date_test[\"date\"])\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2. Advanced Feature Engineering (Deep Context)\n",
        "Injecting insights like cross-promo cannibalization, store capacity, and event interaction effects.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Target Grid\n",
        "target = (\n",
        "    txn[[\"order_id\", \"product_id\", \"units_sold\"]]\n",
        "    .merge(order[[\"order_id\", \"store_id\", \"date\"]], on=\"order_id\", how=\"left\")\n",
        "    .merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "    .groupby([\"store_id\", \"category\", \"date\"], as_index=False)[\"units_sold\"].sum()\n",
        ")\n",
        "target[\"store_id\"] = target[\"store_id\"].astype(int)\n",
        "target[\"date\"] = pd.to_datetime(target[\"date\"])\n",
        "target[\"units_sold\"] = target[\"units_sold\"].astype(\"float32\")\n",
        "\n",
        "stores = sorted(target[\"store_id\"].unique())\n",
        "categories = sorted(target[\"category\"].unique())\n",
        "dates = pd.date_range(TRAIN_START, TRAIN_END, freq=\"D\")\n",
        "date_to_idx = {d: i for i, d in enumerate(dates)}\n",
        "\n",
        "grid = pd.MultiIndex.from_product([stores, categories, dates], names=[\"store_id\", \"category\", \"date\"]).to_frame(index=False)\n",
        "full = grid.merge(target, on=[\"store_id\", \"category\", \"date\"], how=\"left\")\n",
        "full[\"units_sold\"] = full[\"units_sold\"].fillna(0).astype(\"float32\")\n",
        "\n",
        "# Stockout\n",
        "inv = inventory.merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "stockout_cat = inv.groupby([\"store_id\", \"category\", \"date\"], as_index=False).agg(stockout_rate=(\"is_stockout\", \"mean\"))\n",
        "full = full.merge(stockout_cat, on=[\"store_id\", \"category\", \"date\"], how=\"left\")\n",
        "full[\"stockout_rate\"] = full[\"stockout_rate\"].fillna(0).astype(\"float32\")\n",
        "\n",
        "# Store Features\n",
        "store_df = pd.concat([store_train, store_test], ignore_index=True).drop_duplicates(\"store_id\")\n",
        "store_df[\"open_hour\"] = pd.to_numeric(store_df[\"open_time\"].astype(str).str.split(\":\").str[0], errors=\"coerce\").fillna(7)\n",
        "store_df[\"close_hour\"] = pd.to_numeric(store_df[\"close_time\"].astype(str).str.split(\":\").str[0], errors=\"coerce\").fillna(21)\n",
        "store_df[\"operating_hours\"] = store_df[\"close_hour\"] - store_df[\"open_hour\"]\n",
        "store_df[\"capacity_per_staff\"] = store_df[\"seating_capacity\"] / store_df[\"staff_count\"].replace(0, np.nan)\n",
        "store_df[\"has_drive_through\"] = store_df[\"has_drive_through\"].astype(str).str.lower().isin([\"true\", \"1\", \"y\", \"yes\"]).astype(int)\n",
        "\n",
        "neighborhood_dummies = pd.get_dummies(store_df[\"neighborhood_type\"], prefix=\"nbr\").astype(int)\n",
        "expected_nbrs = [\"nbr_airport\", \"nbr_business\", \"nbr_hospital\", \"nbr_mall\", \"nbr_residential\", \"nbr_tourist\", \"nbr_university\"]\n",
        "for col in expected_nbrs:\n",
        "    if col not in neighborhood_dummies: neighborhood_dummies[col] = 0\n",
        "store_features = pd.concat([store_df[[\"store_id\", \"seating_capacity\", \"staff_count\", \"operating_hours\", \"capacity_per_staff\", \"has_drive_through\"]], neighborhood_dummies], axis=1)\n",
        "\n",
        "# Date Features\n",
        "date_all = pd.concat([date_train, date_test], ignore_index=True).drop_duplicates(\"date\")\n",
        "date_all[\"date\"] = pd.to_datetime(date_all[\"date\"])\n",
        "date_all[\"dow\"] = date_all[\"date\"].dt.dayofweek\n",
        "date_all[\"doy\"] = date_all[\"date\"].dt.dayofyear\n",
        "date_all[\"month\"] = date_all[\"date\"].dt.month\n",
        "date_all[\"sin_dow\"] = np.sin(2 * np.pi * date_all[\"dow\"] / 7.0)\n",
        "date_all[\"cos_dow\"] = np.cos(2 * np.pi * date_all[\"dow\"] / 7.0)\n",
        "date_all[\"sin_doy\"] = np.sin(2 * np.pi * date_all[\"doy\"] / 365.25)\n",
        "date_all[\"cos_doy\"] = np.cos(2 * np.pi * date_all[\"doy\"] / 365.25)\n",
        "for col in [\"is_weekend\", \"is_holiday\", \"is_payday\", \"is_school_break\", \"is_rainy_season\"]:\n",
        "    date_all[col] = date_all.get(col, 0).astype(str).str.lower().isin([\"true\", \"1\", \"y\", \"yes\"]).astype(int)\n",
        "\n",
        "# Annual Lags\n",
        "annual_lags = full[[\"store_id\", \"category\", \"date\", \"units_sold\"]].copy()\n",
        "annual_lags = annual_lags.sort_values([\"store_id\", \"category\", \"date\"])\n",
        "for _lag in [364, 365, 366]:\n",
        "    annual_lags[f\"lag_{_lag}\"] = annual_lags.groupby([\"store_id\", \"category\"])[\"units_sold\"].shift(_lag).fillna(0)\n",
        "annual_lags = annual_lags.drop(columns=[\"units_sold\"])\n",
        "full = full.merge(annual_lags, on=[\"store_id\", \"category\", \"date\"], how=\"left\")\n",
        "for _lag in [364, 365, 366]: full[f\"lag_{_lag}\"] = full[f\"lag_{_lag}\"].fillna(0)\n",
        "\n",
        "# Promo Features\n",
        "promo = pd.concat([promo_train, promo_test], ignore_index=True).drop_duplicates()\n",
        "promo = promo.merge(product_train[[\"product_id\", \"category\"]], on=\"product_id\", how=\"left\")\n",
        "promo[\"start_date\"] = pd.to_datetime(promo[\"start_date\"])\n",
        "promo[\"end_date\"] = pd.to_datetime(promo[\"end_date\"])\n",
        "\n",
        "text_cols = [c for c in [\"campaign\", \"campaign_type\", \"campaign_name\", \"campaign_id\"] if c in promo.columns]\n",
        "if text_cols:\n",
        "    pt = promo[text_cols[0]].fillna(\"\").astype(str)\n",
        "    for c in text_cols[1:]: pt = pt + \" \" + promo[c].fillna(\"\").astype(str)\n",
        "    promo[\"promo_text\"] = pt.str.lower()\n",
        "else:\n",
        "    promo[\"promo_text\"] = \"\"\n",
        "\n",
        "promo[\"is_buy1get1\"] = promo[\"promo_text\"].str.contains(\"1แถม1|buy1get1|b1g1|1 แถม 1\").astype(int)\n",
        "promo[\"is_discount\"] = promo[\"promo_text\"].str.contains(\"ลดราคา|discount\").astype(int)\n",
        "promo[\"is_bundle\"] = promo[\"promo_text\"].str.contains(\"ชุดคู่|bundle\").astype(int)\n",
        "\n",
        "promo_rows = []\n",
        "for _, r in promo.iterrows():\n",
        "    if pd.isna(r[\"start_date\"]) or pd.isna(r[\"category\"]): continue\n",
        "    start = max(pd.Timestamp(r[\"start_date\"]), TRAIN_START)\n",
        "    end = min(pd.Timestamp(r[\"end_date\"]), pd.Timestamp(\"2024-12-31\"))\n",
        "    if end < start: continue\n",
        "    store_values = stores if pd.isna(r.get(\"store_id\")) else [int(r[\"store_id\"])]\n",
        "    for store_id in store_values:\n",
        "        for d in pd.date_range(start, end, freq=\"D\"):\n",
        "            promo_rows.append({\n",
        "                \"store_id\": store_id, \"category\": str(r[\"category\"]), \"date\": d,\n",
        "                \"promo_count\": 1, \n",
        "                \"discount_pct\": float(0 if pd.isna(r.get(\"discount_pct\")) else r[\"discount_pct\"]),\n",
        "                \"is_buy1get1\": r[\"is_buy1get1\"],\n",
        "                \"is_discount\": r[\"is_discount\"],\n",
        "                \"is_bundle\": r[\"is_bundle\"]\n",
        "            })\n",
        "p_df = pd.DataFrame(promo_rows)\n",
        "if len(p_df) > 0:\n",
        "    promo_features = p_df.groupby([\"store_id\", \"category\", \"date\"], as_index=False).agg(\n",
        "        promo_count=(\"promo_count\", \"sum\"),\n",
        "        discount_pct=(\"discount_pct\", \"max\"),\n",
        "        is_buy1get1=(\"is_buy1get1\", \"max\"),\n",
        "        is_discount=(\"is_discount\", \"max\"),\n",
        "        is_bundle=(\"is_bundle\", \"max\")\n",
        "    )\n",
        "    # Cross-promo features\n",
        "    p_df[\"is_drink\"] = p_df[\"category\"].isin([\"Coffee\", \"Tea\", \"Juice & Smoothie\", \"Chocolate & Milk\"]).astype(int)\n",
        "    p_df[\"is_merch\"] = (p_df[\"category\"] == \"Merchandise\").astype(int)\n",
        "    store_promo = p_df.groupby([\"store_id\", \"date\"], as_index=False).agg(\n",
        "        drink_promo_active=(\"is_drink\", \"max\"),\n",
        "        merch_promo_active=(\"is_merch\", \"max\")\n",
        "    )\n",
        "    promo_features = promo_features.merge(store_promo, on=[\"store_id\", \"date\"], how=\"left\")\n",
        "else:\n",
        "    promo_features = pd.DataFrame(columns=[\"store_id\", \"category\", \"date\", \"promo_count\", \"discount_pct\", \"is_buy1get1\", \"is_discount\", \"is_bundle\", \"drink_promo_active\", \"merch_promo_active\"])\n",
        "\n",
        "# Event\n",
        "event = pd.concat([event_train, event_test], ignore_index=True).drop_duplicates()\n",
        "event[\"date\"] = pd.to_datetime(event[\"date\"])\n",
        "event_agg = event.groupby([\"store_id\", \"date\"]).agg(\n",
        "    event_count=(\"event_id\", \"nunique\"),\n",
        "    event_types=(\"event_type\", lambda x: \" \".join(x.dropna().astype(str).str.lower()))\n",
        ").reset_index()\n",
        "event_agg[\"event_food_festival\"] = event_agg[\"event_types\"].str.contains(\"food_festival|food festival\").astype(int)\n",
        "event_agg[\"event_music_festival\"] = event_agg[\"event_types\"].str.contains(\"music|concert\").astype(int)\n",
        "event_agg[\"event_cultural\"] = event_agg[\"event_types\"].str.contains(\"cultural|culture\").astype(int)\n",
        "event_agg[\"event_sports\"] = event_agg[\"event_types\"].str.contains(\"sports|marathon\").astype(int)\n",
        "event_features = event_agg.drop(columns=[\"event_types\"])\n",
        "\n",
        "# Merge all into FULL\n",
        "full = full.merge(store_features, on=\"store_id\", how=\"left\")\n",
        "date_cols = [\"date\", \"sin_dow\", \"cos_dow\", \"sin_doy\", \"cos_doy\", \"is_weekend\", \"is_holiday\", \"is_payday\", \"is_school_break\", \"is_rainy_season\"]\n",
        "full = full.merge(date_all[date_cols], on=\"date\", how=\"left\")\n",
        "full = full.merge(promo_features, on=[\"store_id\", \"category\", \"date\"], how=\"left\")\n",
        "full = full.merge(event_features, on=[\"store_id\", \"date\"], how=\"left\")\n",
        "full = full.fillna(0)\n",
        "\n",
        "# Interaction Features\n",
        "full[\"is_coffee\"] = (full[\"category\"] == \"Coffee\").astype(int)\n",
        "full[\"is_juice\"] = (full[\"category\"] == \"Juice & Smoothie\").astype(int)\n",
        "full[\"rainy_x_coffee\"] = full[\"is_rainy_season\"] * full[\"is_coffee\"]\n",
        "full[\"rainy_x_juice\"] = full[\"is_rainy_season\"] * full[\"is_juice\"]\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3. Fast Dense Sequence Tensor Preparation\n",
        "Now with expanded daily sequence channels!\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "store_cat_to_idx = { (s, c): i for i, (s, c) in enumerate([(s, c) for s in stores for c in categories]) }\n",
        "num_series = len(store_cat_to_idx)\n",
        "num_days = len(dates)\n",
        "\n",
        "# Sequence Features (Expanded to 12 channels)\n",
        "seq_features = [\"units_sold\", \"stockout_rate\", \"promo_count\", \"discount_pct\", \n",
        "                \"is_buy1get1\", \"is_holiday\", \"is_payday\", \"is_rainy_season\", \n",
        "                \"is_school_break\", \"event_count\", \"sin_dow\", \"cos_dow\"]\n",
        "num_seq_features = len(seq_features)\n",
        "\n",
        "seq_tensor = np.zeros((num_series, num_days, num_seq_features), dtype=np.float32)\n",
        "\n",
        "full[\"series_idx\"] = full.apply(lambda r: store_cat_to_idx[(r[\"store_id\"], r[\"category\"])], axis=1)\n",
        "full[\"time_idx\"] = full[\"date\"].map(date_to_idx)\n",
        "\n",
        "for i, f in enumerate(seq_features):\n",
        "    seq_tensor[full[\"series_idx\"].values, full[\"time_idx\"].values, i] = full[f].values\n",
        "\n",
        "print(\"Sequence Tensor Shape:\", seq_tensor.shape)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4. PyTorch Dataset\n",
        "Fusing the history tensor with 40+ tabular context features.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "tabular_cols = [\n",
        "    \"sin_dow\", \"cos_dow\", \"sin_doy\", \"cos_doy\", \"is_weekend\", \"is_holiday\", \n",
        "    \"is_payday\", \"is_rainy_season\", \"is_school_break\",\n",
        "    \"promo_count\", \"discount_pct\", \"is_buy1get1\", \"is_discount\", \"is_bundle\", \n",
        "    \"drink_promo_active\", \"merch_promo_active\",\n",
        "    \"event_count\", \"event_food_festival\", \"event_music_festival\", \"event_cultural\", \"event_sports\",\n",
        "    \"seating_capacity\", \"staff_count\", \"operating_hours\", \"capacity_per_staff\", \"has_drive_through\",\n",
        "    \"nbr_airport\", \"nbr_business\", \"nbr_hospital\", \"nbr_mall\", \"nbr_residential\", \"nbr_tourist\", \"nbr_university\",\n",
        "    \"lag_364\", \"lag_365\", \"lag_366\",\n",
        "    \"is_coffee\", \"is_juice\", \"rainy_x_coffee\", \"rainy_x_juice\"\n",
        "]\n",
        "NUM_TAB_FEATURES = len(tabular_cols)\n",
        "\n",
        "class CoffeeDataset(Dataset):\n",
        "    def __init__(self, target_df, seq_tensor, date_to_idx, store_cat_to_idx, mode=\"train\"):\n",
        "        self.target_df = target_df.reset_index(drop=True)\n",
        "        self.seq_tensor = seq_tensor\n",
        "        self.date_to_idx = date_to_idx\n",
        "        self.store_cat_to_idx = store_cat_to_idx\n",
        "        self.mode = mode\n",
        "        \n",
        "    def __len__(self):\n",
        "        return len(self.target_df)\n",
        "    \n",
        "    def __getitem__(self, idx):\n",
        "        row = self.target_df.iloc[idx]\n",
        "        sid, cat = row[\"store_id\"], row[\"category\"]\n",
        "        anchor_date = row[\"anchor_date\"]\n",
        "        \n",
        "        series_i = self.store_cat_to_idx[(sid, cat)]\n",
        "        t_end = self.date_to_idx.get(anchor_date)\n",
        "        if t_end is None: t_end = self.date_to_idx[TRAIN_END]\n",
        "            \n",
        "        t_start = t_end - SEQ_LEN\n",
        "        \n",
        "        if t_start >= 0:\n",
        "            seq_x = self.seq_tensor[series_i, t_start:t_end, :]\n",
        "        else:\n",
        "            seq_x = np.zeros((SEQ_LEN, self.seq_tensor.shape[2]), dtype=np.float32)\n",
        "            valid_len = t_end\n",
        "            if valid_len > 0:\n",
        "                seq_x[-valid_len:, :] = self.seq_tensor[series_i, 0:t_end, :]\n",
        "                \n",
        "        tab_x = np.array([row.get(c, 0) for c in tabular_cols], dtype=np.float32)\n",
        "        \n",
        "        weight = 1.0\n",
        "        if self.mode == \"train\":\n",
        "            rate = row.get(\"target_stockout_rate\", 0)\n",
        "            weight = 1.0 - (1.0 - 0.30) * min(max(rate, 0), 1)\n",
        "            \n",
        "        if self.mode == \"test\":\n",
        "            return torch.tensor(seq_x), torch.tensor(tab_x)\n",
        "        else:\n",
        "            y = np.float32(row[\"target_units_sold\"])\n",
        "            return torch.tensor(seq_x), torch.tensor(tab_x), torch.tensor(y), torch.tensor(weight)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 5. Mamba Hybrid Model Architecture\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "class MambaHybrid(nn.Module):\n",
        "    def __init__(self, seq_in_dim, tab_in_dim, d_model=128, d_state=32, d_conv=4, expand=2):\n",
        "        super().__init__()\n",
        "        \n",
        "        self.seq_proj = nn.Linear(seq_in_dim, d_model)\n",
        "        \n",
        "        self.mamba = Mamba(\n",
        "            d_model=d_model,\n",
        "            d_state=d_state,\n",
        "            d_conv=d_conv,\n",
        "            expand=expand,\n",
        "        )\n",
        "        \n",
        "        self.tab_proj = nn.Sequential(\n",
        "            nn.Linear(tab_in_dim, 64),\n",
        "            nn.GELU(),\n",
        "            nn.LayerNorm(64),\n",
        "            nn.Linear(64, 32)\n",
        "        )\n",
        "        \n",
        "        self.head = nn.Sequential(\n",
        "            nn.Linear(d_model + 32, 128),\n",
        "            nn.GELU(),\n",
        "            nn.LayerNorm(128),\n",
        "            nn.Dropout(0.3),\n",
        "            nn.Linear(128, 64),\n",
        "            nn.GELU(),\n",
        "            nn.Linear(64, 1)\n",
        "        )\n",
        "        \n",
        "    def forward(self, seq_x, tab_x):\n",
        "        x = self.seq_proj(seq_x)\n",
        "        mamba_out = self.mamba(x)\n",
        "        seq_embed = mamba_out.mean(dim=1)\n",
        "        tab_embed = self.tab_proj(tab_x)\n",
        "        \n",
        "        fused = torch.cat([seq_embed, tab_embed], dim=1)\n",
        "        out = self.head(fused)\n",
        "        \n",
        "        return out.squeeze(-1)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 6. Build Train/Test DataFrames & Future Join\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def parse_submission(sample):\n",
        "    out = sample.copy()\n",
        "    parsed = out[\"id\"].str.extract(r\"^(\\d+)_(.+)_(\\d{4}-\\d{2}-\\d{2})_(1d|7d|1m)$\")\n",
        "    out[[\"store_id\", \"category\", \"forecast_date\", \"horizon\"]] = parsed\n",
        "    out[\"store_id\"] = out[\"store_id\"].astype(int)\n",
        "    out[\"forecast_date\"] = pd.to_datetime(out[\"forecast_date\"])\n",
        "    out[\"h\"] = out[\"horizon\"].map(HORIZON_TO_DAYS).astype(int)\n",
        "    out[\"decision_date\"] = out[\"forecast_date\"] - pd.to_timedelta(out[\"h\"], unit=\"D\")\n",
        "    return out\n",
        "\n",
        "parsed_sample = parse_submission(sample)\n",
        "\n",
        "# Build Future lookup dataframe\n",
        "future_features = full[[\"store_id\", \"category\", \"date\"] + tabular_cols].copy()\n",
        "future_features = future_features.rename(columns={\"date\": \"forecast_date\"})\n",
        "\n",
        "def add_future_covariates(df):\n",
        "    out = df.merge(future_features, on=[\"store_id\", \"category\", \"forecast_date\"], how=\"left\")\n",
        "    return out.fillna(0)\n",
        "\n",
        "train_frames = []\n",
        "for horizon, h in HORIZON_TO_DAYS.items():\n",
        "    base = full[[\"store_id\", \"category\", \"date\", \"units_sold\", \"stockout_rate\"]].rename(\n",
        "        columns={\"date\": \"forecast_date\", \"units_sold\": \"target_units_sold\", \"stockout_rate\": \"target_stockout_rate\"}\n",
        "    )\n",
        "    base[\"horizon\"] = horizon\n",
        "    base[\"h\"] = h\n",
        "    base[\"decision_date\"] = base[\"forecast_date\"] - pd.to_timedelta(h, unit=\"D\")\n",
        "    base[\"anchor_date\"] = base[\"decision_date\"]\n",
        "    \n",
        "    base = base[(base[\"anchor_date\"] >= TRAIN_START) & (base[\"forecast_date\"] <= TRAIN_END)].copy()\n",
        "    base = add_future_covariates(base)\n",
        "    train_frames.append(base)\n",
        "\n",
        "train_all = pd.concat(train_frames, ignore_index=True)\n",
        "\n",
        "test_all = parsed_sample.copy()\n",
        "test_all[\"anchor_date\"] = test_all[\"decision_date\"].clip(upper=TRAIN_END)\n",
        "test_all = add_future_covariates(test_all)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 7. Training Loop\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "def train_horizon(horizon):\n",
        "    print(f\"\\n{'='*40}\\nTraining Mamba for Horizon: {horizon}\\n{'='*40}\")\n",
        "    df_h = train_all[train_all[\"horizon\"] == horizon].copy()\n",
        "    \n",
        "    train_df = df_h[df_h[\"forecast_date\"] < \"2023-11-01\"]\n",
        "    valid_df = df_h[df_h[\"forecast_date\"].between(\"2023-11-01\", \"2023-12-31\")]\n",
        "    \n",
        "    train_ds = CoffeeDataset(train_df, seq_tensor, date_to_idx, store_cat_to_idx, mode=\"train\")\n",
        "    valid_ds = CoffeeDataset(valid_df, seq_tensor, date_to_idx, store_cat_to_idx, mode=\"valid\")\n",
        "    \n",
        "    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)\n",
        "    valid_loader = DataLoader(valid_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
        "    \n",
        "    model = MambaHybrid(seq_in_dim=num_seq_features, tab_in_dim=NUM_TAB_FEATURES).to(device)\n",
        "    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
        "    criterion = nn.L1Loss(reduction='none')\n",
        "    \n",
        "    best_mae = float('inf')\n",
        "    best_weights = None\n",
        "    \n",
        "    for epoch in range(EPOCHS):\n",
        "        model.train()\n",
        "        train_loss = 0.0\n",
        "        for seq_x, tab_x, y, weight in train_loader:\n",
        "            seq_x, tab_x, y, weight = seq_x.to(device), tab_x.to(device), y.to(device), weight.to(device)\n",
        "            \n",
        "            optimizer.zero_grad()\n",
        "            preds = model(seq_x, tab_x)\n",
        "            loss = (criterion(preds, y) * weight).mean()\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            train_loss += loss.item() * seq_x.size(0)\n",
        "            \n",
        "        train_loss /= len(train_loader.dataset)\n",
        "        \n",
        "        model.eval()\n",
        "        valid_loss = 0.0\n",
        "        with torch.no_grad():\n",
        "            for seq_x, tab_x, y, weight in valid_loader:\n",
        "                seq_x, tab_x, y = seq_x.to(device), tab_x.to(device), y.to(device)\n",
        "                preds = torch.relu(model(seq_x, tab_x))\n",
        "                loss = nn.L1Loss()(preds, y)\n",
        "                valid_loss += loss.item() * seq_x.size(0)\n",
        "        valid_loss /= len(valid_loader.dataset)\n",
        "        \n",
        "        print(f\"Epoch {epoch+1:02d} | Train L1: {train_loss:.4f} | Valid MAE: {valid_loss:.4f}\")\n",
        "        \n",
        "        if valid_loss < best_mae:\n",
        "            best_mae = valid_loss\n",
        "            best_weights = model.state_dict().copy()\n",
        "            \n",
        "    print(f\"Best Valid MAE: {best_mae:.4f}\")\n",
        "    \n",
        "    print(\"Retraining on full data...\")\n",
        "    full_ds = CoffeeDataset(df_h, seq_tensor, date_to_idx, store_cat_to_idx, mode=\"train\")\n",
        "    full_loader = DataLoader(full_ds, batch_size=BATCH_SIZE, shuffle=True)\n",
        "    \n",
        "    model.load_state_dict(best_weights)\n",
        "    optimizer = torch.optim.AdamW(model.parameters(), lr=LR/2)\n",
        "    \n",
        "    model.train()\n",
        "    for epoch in range(2):\n",
        "        for seq_x, tab_x, y, weight in full_loader:\n",
        "            seq_x, tab_x, y, weight = seq_x.to(device), tab_x.to(device), y.to(device), weight.to(device)\n",
        "            optimizer.zero_grad()\n",
        "            preds = model(seq_x, tab_x)\n",
        "            loss = (criterion(preds, y) * weight).mean()\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "            \n",
        "    return model\n",
        "\n",
        "trained_models = {}\n",
        "for horizon in [\"1d\", \"7d\", \"1m\"]:\n",
        "    trained_models[horizon] = train_horizon(horizon)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 8. Inference & Submission\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "submission = sample[[\"id\"]].copy()\n",
        "submission[\"units_sold_predicted\"] = np.nan\n",
        "\n",
        "for horizon in [\"1d\", \"7d\", \"1m\"]:\n",
        "    idx = test_all[\"horizon\"] == horizon\n",
        "    test_df = test_all.loc[idx]\n",
        "    \n",
        "    test_ds = CoffeeDataset(test_df, seq_tensor, date_to_idx, store_cat_to_idx, mode=\"test\")\n",
        "    test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)\n",
        "    \n",
        "    model = trained_models[horizon]\n",
        "    model.eval()\n",
        "    \n",
        "    all_preds = []\n",
        "    with torch.no_grad():\n",
        "        for seq_x, tab_x in test_loader:\n",
        "            seq_x, tab_x = seq_x.to(device), tab_x.to(device)\n",
        "            preds = torch.relu(model(seq_x, tab_x))\n",
        "            all_preds.extend(preds.cpu().numpy().tolist())\n",
        "            \n",
        "    submission.loc[idx.values, \"units_sold_predicted\"] = all_preds\n",
        "    print(f\"Horizon {horizon} predictions mean: {np.mean(all_preds):.4f}\")\n",
        "\n",
        "submission.to_csv(OUTPUT_PATH, index=False)\n",
        "print(\"\\nSaved to\", OUTPUT_PATH)\n",
        "display(submission.head())\n"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.12.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

with open(r"Level 2\Hackathon 5_Demand Forecasting Coffee Chain Hackathon\hackathon-5-mamba-hybrid-v1.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("Notebook generated successfully!")
